# Generated by Django 5.2.5 on 2025-08-29 17:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id_str', models.CharField(db_index=True, max_length=100, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('WIRE', 'WireTransfer'), ('EQUITY', 'Equity Trade'), ('FX', 'FX Spot'), ('CRYPTO', 'Crypto Trade')], default='WIRE', max_length=10)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency', models.CharField(max_length=5)),
                ('client_name', models.CharField(max_length=255)),
                ('source_account', models.CharField(max_length=100)),
                ('destination_account', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('COMPLIANT', 'Compliant'), ('HIGH_RISK', 'High-Risk'), ('BLOCKED', 'Blocked')], db_index=True, default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='XaiExplanation',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='transactions.transaction')),
                ('base_value', models.FloatField()),
                ('shap_values', models.JSONField()),
                ('feature_names', models.JSONField()),
                ('feature_values', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
